import Head from 'next/head'
import Image from 'next/image'
import Router from 'next/router'
import React from 'react'
import { useEffect } from 'react'




export default function Contact() {


useEffect(() => {
   const {pathname} = Router
   if(pathname == '/contact' ){
       Router.push('/')
   }
 });


  return (
    <div>
      <Head>
        <title>Vercel Interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <h1>Contact</h1>
    </div>
  )
}
