import Head from "next/head";

import { Container, Card, Row, Text } from "@nextui-org/react";

const BeforeVisiting = [
  {
    task: "Make sure you have researched the year, make, model of the car you are looking for.",
  },
  {
    task: "Call the dealership to inquire on the specific car you are looking for, this is a perfect time to interview your sales person to see if they are knowledgable on the product they are selling",
  },
  {
    task: "Ask the saleperson to send some pictures of the car to your email so you can take a look at it and make sure that the car is there before you make the drive",
  },
  {
    task: "Make an appointment to go take a look at the car. Try to make an appointment during the week, in my experience, Tuesday or Thursday are the best days to buy a car",
  },
  {
    task: "Have your Drivers License and proof of car insurance so you can go on a demonstration drive with the car you want",
  },
];

const AtTheDealerShip = [
  {
    task: "Before going on a test drive, take a look around at the dealership. Access if this is a place you want to spend your money at",
  },
  {
    task: "Idenitfy the salesperson you talked to on the phone or via email. This is the person you want to ask all your questions too",
  },
  {
    task: "Ask to see the car, look for small details: (ex: did the sales person wash the car, did they pull up the car before you arrived, did they make sure the car did not smell funny, etc) ",
  },
  {
    task: "Once you are on the test drive, focus on driving. Remember you did your homework on the car features, ask some questions about features to the salesperson to see if they are being honest ",
  },
];

export default function Task() {
  const items = BeforeVisiting.map((item) => (
    // eslint-disable-next-line react/jsx-key
    <div style={{ marginTop: "2rem" }}>
      <Container fluid>
        <Card style={{ backgroundColor: "black" }}>
          <Card.Body key={item.task}>
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              {item.task}
            </Text>
          </Card.Body>
        </Card>
      </Container>
    </div>
  ));

  const dislikeItem = AtTheDealerShip.map((item) => (
    // eslint-disable-next-line react/jsx-key
    <div style={{ marginTop: "2rem" }}>
      <Container fluid>
        <Card style={{ backgroundColor: "black" }}>
          <Card.Body key={item.task}>
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              {item.task}
            </Text>
          </Card.Body>
        </Card>
      </Container>
    </div>
  ));

  return (
    <div>
      <Head>
        <title>Task Response</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ marginTop: "1rem", marginLeft: "1rem" }}>
        <h1> Before visiting the Dealership: </h1>
      </div>

      <div style={{ paddingBottom: "50px" }}>{items}</div>

      <div>
        <h1 style={{ marginTop: "1rem", marginLeft: "1rem" }}>
          Once you are at the dealership:{" "}
        </h1>

        <div style={{ paddingBottom: "50px" }}>{dislikeItem}</div>
      </div>
    </div>
  );
}
