import Head from 'next/head'
import Image from 'next/image'
import { Container, Card, Row, Text } from '@nextui-org/react'


export default function Task() {
  return (
    <div>
      <Head>
        <title>Task Response</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style ={{ marginTop: '1rem', marginLeft: '1rem'}}>
      <h1> Things a Product Advocate might do that I like:  </h1> 
      </div>
        

      <div style ={{marginTop: '2rem'}}> 
      <Container fluid >
      <Card style = {{backgroundColor: 'black'}}>
        <Card.Body>
          
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              NextUI gives you the best developer experience with all the features
              you need for building beautiful and modern websites and
              applications.
            </Text>
          
        </Card.Body>
      </Card>
    </Container>
      </div> 

      <div style ={{marginTop: '5rem'}}> 
      <Container>
      <Card style = {{backgroundColor: 'black'}}>
        <Card.Body>
          
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              NextUI gives you the best developer experience with all the features
              you need for building beautiful and modern websites and
              applications.
            </Text>
          
        </Card.Body>
      </Card>
    </Container>
      </div> 
      <div style ={{marginTop: '5rem'}}> 
      <Container>
      <Card style = {{backgroundColor: 'black'}}>
        <Card.Body>
          
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              NextUI gives you the best developer experience with all the features
              you need for building beautiful and modern websites and
              applications.
            </Text>
          
        </Card.Body>
      </Card>
    </Container>
      </div> 

      <div style ={{marginTop: '5rem'}}> 
      <Container>
      <Card style = {{backgroundColor: 'black'}}>
        <Card.Body>
          
            <Text h6 size={15} color="white" css={{ m: 0 }}>
              NextUI gives you the best developer experience with all the features
              you need for building beautiful and modern websites and
              applications.
            </Text>
          
        </Card.Body>
      </Card>
    </Container>
      </div> 
    </div>
  )
}
